# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstore.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kvstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvstore.proto\x12\x07kvstore\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x08OldValue\x12\x11\n\told_value\x18\x01 \x01(\t\"\x17\n\x07KeyList\x12\x0c\n\x04keys\x18\x01 \x03(\t\"0\n\x0c\x42\x61\x63kupStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9d\x02\n\rKeyValueStore\x12+\n\x03Put\x12\x11.kvstore.KeyValue\x1a\x11.kvstore.OldValue\x12#\n\x03Get\x12\x0c.kvstore.Key\x1a\x0e.kvstore.Value\x12&\n\x06\x44\x65lete\x12\x0c.kvstore.Key\x1a\x0e.kvstore.Empty\x12,\n\x08ListKeys\x12\x0e.kvstore.Empty\x1a\x10.kvstore.KeyList\x12/\n\x06\x42\x61\x63kup\x12\x0e.kvstore.Empty\x1a\x15.kvstore.BackupStatus\x12\x33\n\x04Ping\x12\x14.kvstore.PingRequest\x1a\x15.kvstore.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUE']._serialized_start=26
  _globals['_KEYVALUE']._serialized_end=64
  _globals['_KEY']._serialized_start=66
  _globals['_KEY']._serialized_end=84
  _globals['_VALUE']._serialized_start=86
  _globals['_VALUE']._serialized_end=108
  _globals['_OLDVALUE']._serialized_start=110
  _globals['_OLDVALUE']._serialized_end=139
  _globals['_KEYLIST']._serialized_start=141
  _globals['_KEYLIST']._serialized_end=164
  _globals['_BACKUPSTATUS']._serialized_start=166
  _globals['_BACKUPSTATUS']._serialized_end=214
  _globals['_EMPTY']._serialized_start=216
  _globals['_EMPTY']._serialized_end=223
  _globals['_PINGREQUEST']._serialized_start=225
  _globals['_PINGREQUEST']._serialized_end=238
  _globals['_PINGRESPONSE']._serialized_start=240
  _globals['_PINGRESPONSE']._serialized_end=271
  _globals['_KEYVALUESTORE']._serialized_start=274
  _globals['_KEYVALUESTORE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
